import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

// フォントの設定
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// ページメタデータ
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ルートレイアウト
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 全体をProtectedRouteで保護 */}
        
          {/* ヘッダー */}
          <header className="bg-blue-600 text-white p-4">
            <div className="container mx-auto flex justify-between items-center">
              <h1 className="text-2xl font-bold">Dekoboko App</h1>
              <nav>
                <ul className="flex space-x-4">
                  <li>
                    <Link href="/" className="hover:underline">
                      Home
                    </Link>
                  </li>
                  <li>
                    <Link href="/profile" className="hover:underline">
                      Profile
                    </Link>
                  </li>
                  <li>
                    <Link href="/about" className="hover:underline">
                      About
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>

          {/* メインコンテンツ */}
          <main className="container mx-auto py-8">{children}</main>

          {/* フッター */}
          <footer className="bg-gray-800 text-white text-center p-4">
            <p>© 2025 Dekoboko App. All Rights Reserved.</p>
          </footer>
        
      </body>
    </html>
  );
}
